/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -types
Author: Bastien Genbrugge (https://sketchfab.com/bastienBGR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ship-in-clouds-c475323dc7f24e26ba2009c08c8e1941
Title: Ship in Clouds
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Sky_Mat_0: THREE.Mesh;
    Boot_Finaal_1_Boot_Finaal_0: THREE.Mesh;
    Cloud_Poly_Poly_0: THREE.Mesh;
    Cloud_1_Cloud_1_0: THREE.Mesh;
    Cloud_2_Cloud_2_0: THREE.Mesh;
    Cloud_3_Cloud_3_0: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
    Boot_Finaal: THREE.MeshStandardMaterial;
    Poly: THREE.MeshStandardMaterial;
    Cloud_1: THREE.MeshStandardMaterial;
    Cloud_2: THREE.MeshStandardMaterial;
    Cloud_3: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/shipInClouds/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sky_Mat_0.geometry}
            material={materials.material}
            position={[51.64, 0, -817.58]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boot_Finaal_1_Boot_Finaal_0.geometry}
            material={materials.Boot_Finaal}
            position={[7.53, -7.8, -688.48]}
            rotation={[0, -0.6, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cloud_Poly_Poly_0.geometry}
            material={materials.Poly}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cloud_1_Cloud_1_0.geometry}
            material={materials.Cloud_1}
            position={[-102.34, -152.02, -1209.99]}
            rotation={[1.92, 0.43, 0.91]}
            scale={1.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cloud_2_Cloud_2_0.geometry}
            material={materials.Cloud_2}
            position={[333.05, -63.93, -1541.73]}
            rotation={[-2.9, 0.21, -1.17]}
            scale={1.5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cloud_3_Cloud_3_0.geometry}
            material={materials.Cloud_3}
            position={[339.37, -70.97, -1571.75]}
            rotation={[2.89, -1.31, 3.08]}
            scale={1.19}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
